export const enumOfPersonCategory = {
  ALUNO: 1,
  PROFESSOR: 2,
  MONITOR_DE_INFORMATICA: 3,
  SECRETARIO: 4,
  COORDENADOR: 5,
  VICE_DIRETOR: 6,
  DIRETOR: 7,
  SUPERVISOR: 8,
  RESPONSAVEL: 9,
  PAIS: 10,
  ADMINISTRADOR: 11,
  OUTROS: 12
}
